# Logstash Configuration for Production DevOps Pipeline
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
xpack.monitoring.enabled: true

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue settings
queue.type: memory
queue.max_bytes: 1024mb

# Logging
log.level: info
log.format: json
