server:
  port: 8080

spring:
  application:
    name: devops-performance-demo

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:development}

logging:
  level:
    com.devops: DEBUG
    org.springframework.web: INFO
