version: '3.8'

services:
  jenkins-metrics-bridge:
    build:
      context: .
      dockerfile: Dockerfile.metrics
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true
